SELECT * FROM EMP7;

--SELECT MAXIMUM SALARY
SELECT MAX(ESAL) FROM EMP7;

--SELECT MINIMUM SALARY
SELECT MIN(ESAL) FROM EMP7;

--DISPLAY AVERAGE SALARY OF ALL EMPLOYEES
SELECT AVG(ESAL) FROM EMP7;

--DISPLAY SUM OF ALL SALARY
SELECT SUM(ESAL) FROM EMP7;

--DISPLAY COUNT OF RECORDS(EXCLUDING NULL), USING COUNT(COLUMN_NAME)
SELECT COUNT(EID)AS EXCLUDING_NULL_RECORDS FROM EMP7;

--DISPLAY COUNT OF RECORDS(INCLUDING NULL), USING COUNT(*)
SELECT COUNT(EID)AS INCLUDING_NULL_RECORDS FROM EMP7;