SELECT * FROM EMP7;

--A. CHARACTER MANIPULATION
--A_1. LENGTH()
SELECT LENGTH(ENAME) FROM EMP7;

--OR

SELECT LENGTH('DESHBHRATAR') FROM DUAL;

--OR

SELECT LENGTH(ENAME) FROM EMP7
WHERE EID = 630;

--A_2. SUBSTR()
SELECT SUBSTR('DESHBHRATAR', 5, 4) FROM DUAL;

-- OR

SELECT SUBSTR(EMAIL, 10, 5) FROM EMP7;

--OR

SELECT SUBSTR(EMAIL, 20, 8) FROM EMP7
WHERE EID = 186;

--A_3 INSTR()
SELECT INSTR('DESHBHRATAR', 'H') FROM DUAL;
--OR
SELECT INSTR('DESHBHRATAR', 'H', 1, 1) FROM DUAL;
--OR
SELECT INSTR('DESHBHRATAR', 'H', 1, 2) FROM DUAL;

--B. CASE MANIPULATION OR SCALAR FUNCTION
--A_1. LOWER
SELECT LOWER(ENAME) FROM EMP7
WHERE EID = 480;

--A_2. UPPER
SELECT UPPER(EMAIL) FROM EMP7
WHERE EID = 874;

--A_3. INITCAP()
SELECT INITCAP('rohit deshbhratar') FROM DUAL;
