SELECT * FROM EMP7;

--DISPLAY DUPLICATE RECORDS
SELECT 
    EID, COUNT(*)
FROM 
    EMP7
GROUP BY
    EID
HAVING COUNT(EID) > 1;

-- OR
SELECT
    EID, ENAME, EMOB,ESAL, EDOJ, EDOR, EMAIL, ECITY
FROM
    EMP7
GROUP BY
    EID, ENAME, EMOB,ESAL, EDOJ, EDOR, EMAIL, ECITY
HAVING
    COUNT(*) > 1;

--DISPLAY UNIQUE RECORDS
SELECT
    EID, ENAME, EMOB,ESAL, EDOJ, EDOR, EMAIL, ECITY
FROM
    EMP7
GROUP BY
    EID, ENAME, EMOB,ESAL, EDOJ, EDOR, EMAIL, ECITY
HAVING
    COUNT(*) = 1
ORDER BY
    EID;

--OR
SELECT
    EID, COUNT(*)
FROM
    EMP7
GROUP BY
    EID
HAVING
    COUNT(*) = 1
ORDER BY
    EID;
    
--SCENARIOS IN HAVING CLAUSE
--1 FIND DEPARTMENTS WHERE SALARY IS GREATER THAN 10,000
SELECT
    EDEPT, MAX(ESAL)AS SAL_MORE_THAN_10K
FROM
    EMP7
GROUP BY
    EDEPT
HAVING
    MAX(ESAL) > 10000
ORDER BY
    SAL_MORE_THAN_10K;
    
--2 FIND DEPARTMENT WISE TOTAL SALARY WHERE SALARY IS > 400000.
SELECT
    EDEPT, SUM(ESAL)AS DEPT_WISE_SUM_OF_SAL
FROM 
    EMP7
GROUP BY
    EDEPT
HAVING 
    SUM(ESAL) > 400000
ORDER BY
    DEPT_WISE_SUM_OF_SAL;
    
--3 FIND DEPARTMENT WHOSE AVG SALARY IS > 12000.
SELECT
    EDEPT, AVG(ESAL)AS DEPT_WISE_AVG_SAL
FROM 
    EMP7
GROUP BY
    EDEPT
HAVING 
    AVG(ESAL) > 12000
ORDER BY
    DEPT_WISE_AVG_SAL;
    
--4 DISPLAY COUNT OF EMPLOYEES HAVING SALARY > 20000 IN ALL DEPARTMENTS
SELECT
    EDEPT, COUNT(*)AS DEPT_WISE_AVG_SAL
FROM 
    EMP7
WHERE 
    ESAL > 20000
GROUP BY
    EDEPT
HAVING 
    MAX(ESAL) > 20000
ORDER BY
    DEPT_WISE_AVG_SAL;



