SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;
SELECT * FROM COUNTRIES;
SELECT * FROM JOB_HISTORY;
SELECT * FROM LOCATIONS;
SELECT * FROM REGIONS;
--------------------------------------------------------------------------------
-- INNER JOIN
--DISPLAY NAME OF EMPLOYEES AND NAME OF DEPARTMENT IN WHICH THEY ARE WORKING.
SELECT 
    E.EMPLOYEE_ID, ((E.FIRST_NAME)||' '||(E.LAST_NAME))AS FULL_NAME,
        D.DEPARTMENT_NAME
FROM 
    EMPLOYEES E
INNER JOIN
    DEPARTMENTS D
ON 
    E.DEPARTMENT_ID = D.DEPARTMENT_ID;
    
--DISPLAY NAME OF EMPLOYEE, DEPARTMENT NAME AND JOB TITLE
SELECT
    E.EMPLOYEE_ID, ((FIRST_NAME)||' '||(E.LAST_NAME))AS FULL_NAME,
    D.DEPARTMENT_NAME AS DEPARTMENT, J.JOB_TITLE AS WORKS_AS
FROM
    EMPLOYEES E
INNER JOIN
    DEPARTMENTS D
ON
    D.DEPARTMENT_ID = E.DEPARTMENT_ID
INNER JOIN
    JOBS J
ON
    E.JOB_ID = J.JOB_ID;
    
--DISPLAY LOCATIONS OF VARIOUS DEPARTMENTS
SELECT
    D.DEPARTMENT_NAME, L.CITY, C.COUNTRY_NAME
FROM
    DEPARTMENTS D
INNER JOIN
    LOCATIONS L
ON
    D.LOCATION_ID = L.LOCATION_ID
INNER JOIN
    COUNTRIES C
ON
    L.COUNTRY_ID = C.COUNTRY_ID;
    
-- DISPLAY WORKING EXPERIENCE OF EMPLOYEES IN VARIOUS DEPARTMENTS
SELECT
    E.EMPLOYEE_ID, D.DEPARTMENT_NAME,
    TRUNC(MONTHS_BETWEEN(JH.END_DATE, JH.START_DATE) / 12)AS EXP_YEAR,
    TRUNC(MOD(MONTHS_BETWEEN(JH.END_DATE, JH.START_DATE), 12))AS EXP_MONTHS,
    TRUNC(JH.END_DATE-ADD_MONTHS(JH.START_DATE,TRUNC(MONTHS_BETWEEN(JH.END_DATE, JH.START_DATE)/12)*12+
    TRUNC(Mod(MONTHS_BETWEEN(JH.END_DATE, JH.START_DATE),12)))) EXP_DAY
FROM
    EMPLOYEES E
INNER JOIN
    DEPARTMENTS D
ON
    E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN
    JOB_HISTORY JH
ON
    E.EMPLOYEE_ID = JH.EMPLOYEE_ID;
--------------------------------------------------------------------------------
--LEFT OUTER JOIN OR LEFT JOIN
--APPLY LEFT JOIN ON COUNTRIES AND LOCATIONS TABLES, STUDY THE RESULT.
--BELOW QUERY RETURN 34 ROWS.
SELECT
    L.STREET_ADDRESS, L.POSTAL_CODE, L.CITY, L.STATE_PROVINCE, C.COUNTRY_NAME
FROM 
    COUNTRIES C
LEFT JOIN
    LOCATIONS L
ON
    C.COUNTRY_ID = L.COUNTRY_ID
ORDER BY C.COUNTRY_NAME;

--APPLY LEFT JOIN ON LOCATIONS AND COUNTRIES TABLES, STUDY THE RESULT.
--BELOW QUERY RETURN 23 ROWS.
SELECT
    L.STREET_ADDRESS, L.POSTAL_CODE, L.CITY, L.STATE_PROVINCE, C.COUNTRY_NAME
FROM 
    LOCATIONS L
LEFT JOIN
    COUNTRIES C
ON
    L.COUNTRY_ID = C.COUNTRY_ID
ORDER BY C.COUNTRY_NAME;
--------------------------------------------------------------------------------
--RIGHT OUTER JOIN OR RIGHT JOIN
--APPLY RIGHT JOIN ON DEPARTMENT AND LOCATIONS TBALE, STUDY THE RESULT.
--RETURN 43 RECORDS WITH 'NULL' VALUE IN DEPARTMENT_NAME
SELECT
    D.DEPARTMENT_NAME, L.CITY, L.STATE_PROVINCE
FROM
    DEPARTMENTS D
RIGHT JOIN
    LOCATIONS L
ON
    D.LOCATION_ID = L.LOCATION_ID
ORDER BY D.DEPARTMENT_NAME NULLS LAST;

--APPLY RIGHT JOIN ON LOCATIONS AND DEPARTMENT TBALE, STUDY THE RESULT.
--RETURN 27 RECORDS WITH NO 'NULL' VALUE IN DEPARTMENT_NAME
SELECT
    D.DEPARTMENT_NAME, L.CITY, L.STATE_PROVINCE
FROM
    LOCATIONS L
RIGHT JOIN
    DEPARTMENTS D
ON
    L.LOCATION_ID = D.LOCATION_ID
ORDER BY D.DEPARTMENT_NAME NULLS LAST;
--------------------------------------------------------------------------------
--FULL OUTER JOIN
--APPLY FULL OUTER JOIN ON EMPLOYEES AND JOB_HISTORY TABLES, STUDY THE RESULT.
--RETURN 110 RECORDS FOR MATCHING DATA.
SELECT
    E.EMPLOYEE_ID, JH.JOB_ID
FROM
    EMPLOYEES E
FULL OUTER JOIN
    JOB_HISTORY JH
ON
    E.EMPLOYEE_ID = JH.EMPLOYEE_ID
ORDER BY JH.JOB_ID NULLS LAST;
--------------------------------------------------------------------------------
--CROSS JOIN
--APPLY CROSS JOIN ON REGIONS AND COUNTRIES TABLE.
--COUNTRIES TABLE HAS 25 RECORDS AND REGIONS TABLE HAS 4 RECORDS.
--TOTAL RECORDS RETURNED BY BELOW QUERY IS 100
SELECT
    C.COUNTRY_NAME, R.REGION_NAME
FROM
    COUNTRIES C
CROSS JOIN
    REGIONS R
ORDER BY
    C.COUNTRY_NAME;
--------------------------------------------------------------------------------
--SELF JOIN
--FIND MANAGER ID OF EACH EMPLOYEE.
SELECT
    E1.EMPLOYEE_ID, ((E1.FIRST_NAME)||' '||(E1.LAST_NAME))AS MANAGER_NAME,
    ((E2.FIRST_NAME)||' '||(E2.LAST_NAME))AS EMPLOYEE_NAME
FROM 
    EMPLOYEES E1
INNER JOIN
    EMPLOYEES E2
ON
    E1.EMPLOYEE_ID = E2.MANAGER_ID
ORDER BY
    E1.EMPLOYEE_ID;
--------------------------------------------------------------------------------
--EQUI JOIN
--RETURNS ALL COLUMNS PRESENT IN 'EMPLOYEES' AND 'DEPARTMENTS' TABLE.
SELECT * 
FROM 
    EMPLOYEES E, DEPARTMENTS D
WHERE
    E.DEPARTMENT_ID = D.DEPARTMENT_ID;
--------------------------------------------------------------------------------
--NON EQUI JOIN
--RETURNS ALL COLUMNS PRESENT IN 'COUNTRIES' AND 'LOCATIONS' TABLE.
SELECT * 
FROM 
    COUNTRIES C, LOCATIONS L
WHERE
    C.COUNTRY_ID != L.COUNTRY_ID;
--------------------------------------------------------------------------------
