SELECT * FROM EMPLOYEES;

/*SELECT MAXIMUM SALARY*/
SELECT MAX(SALARY) FROM EMPLOYEES;

/*SELECT MAX SALARY WITH DETAILS*/
SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

SELECT * FROM EMPLOYEES
WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEES);

/*SELECT SECOND MAXIMUM SALARY USING SUBQUERY*/
SELECT MAX(SALARY) FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES);

SELECT MAX(SALARY) FROM EMPLOYEES
WHERE SALARY != (SELECT MAX(SALARY) FROM EMPLOYEES);

SELECT MAX(SALARY) FROM EMPLOYEES
WHERE SALARY NOT IN (SELECT MAX(SALARY) FROM EMPLOYEES);

/*SELECT SECOND MAXIMUM SALARY WITH DETAILS USING SUBQUERY*/
SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES
                WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES));
                
SELECT * FROM EMPLOYEES
WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEES
                WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES));
                
/*SELECT THIRD MAXIMUM SALARY USING SUBQUERY*/
SELECT MAX(SALARY) FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES
                WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES));

SELECT MAX(SALARY) FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES
                WHERE SALARY NOT IN (SELECT MAX(SALARY) FROM EMPLOYEES));
                
/*SELECT THIRD MAXIMUM SALARY WITH DETAILS USING SUBQUERY*/
SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES
                WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES
                    WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES)));

SELECT * FROM EMPLOYEES
WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEES
                WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES
                    WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES)));