SELECT * FROM EMPLOYEES;

/*SELECT MINIMUM SALARY OF EMPLOYEE*/
SELECT MIN(SALARY) FROM EMPLOYEES;

/*SELECT MINIMUM SALARY OF EMPLOYEE WITH DETAILS USING SUBQUERY*/
SELECT * FROM EMPLOYEES
WHERE SALARY IN (SELECT MIN(SALARY) FROM EMPLOYEES);

SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);

/*SELECT SECOND MINIMUM SALARY OF EMPLOYEE USING SUBQUERY*/
SELECT MIN(SALARY) FROM EMPLOYEES
WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES);

SELECT MIN(SALARY) FROM EMPLOYEES
WHERE SALARY != (SELECT MIN(SALARY) FROM EMPLOYEES);

SELECT MIN(SALARY) FROM EMPLOYEES
WHERE SALARY NOT IN (SELECT MIN(SALARY) FROM EMPLOYEES);

/*SELECT SECOND MINIMUM SALARY OF EMPLOYEE WITH DETAILS USING SUBQUERY*/
SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES
                WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES));
                
SELECT * FROM EMPLOYEES
WHERE SALARY IN (SELECT MIN(SALARY) FROM EMPLOYEES
                WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES));
                
SELECT * FROM EMPLOYEES
WHERE SALARY IN (SELECT MIN(SALARY) FROM EMPLOYEES
                WHERE SALARY NOT IN (SELECT MIN(SALARY) FROM EMPLOYEES));
                
SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES
                WHERE SALARY NOT IN (SELECT MIN(SALARY) FROM EMPLOYEES));

-- SELECT THIRD MINIMUM SALARY.
SELECT MIN(SALARY) FROM EMPLOYEES
WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES
                WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES));

-- SELECT THIRD MINIMUM SALARY WITH DETAILS.
SELECT * FROM EMPLOYEES
WHERE SALARY IN (SELECT MIN(SALARY) FROM EMPLOYEES
                WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES
                    WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES)));
                    
SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES
                WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES
                    WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES)));
