SELECT * FROM EMPLOYEES;

--DISPLAY ROWID OF ALL RECORDS IN ASCENDING ORDER
SELECT ROWID FROM EMPLOYEES
ORDER BY ROWID;

--DISPLAY ROWID WITH DETAILS
SELECT EMPLOYEES.*, ROWID FROM EMPLOYEES;

--DISPLAY ROWID IN DESCENDING ORDER
SELECT EMPLOYEES.*, ROWID FROM EMPLOYEES ORDER BY ROWID DESC;

--------------------------------------------------------------------------------
--INTERVIWE QUESTION
--DISPLAY DEPARTMENT WISE FIRST INSERTED RECORD
SELECT DEPARTMENT_ID, MIN(ROWID) FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

--DISPLAY FIRST INSERTED RECORD WITH DETAILS
SELECT EMPLOYEES.*, ROWID FROM EMPLOYEES
WHERE ROWID IN (SELECT MIN(ROWID) FROM EMPLOYEES);

--DISPLAY DEPARTMENT WISE LAST INSERTED RECORD
SELECT DEPARTMENT_ID, MAX(ROWID) FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

--DISPLAY LAST INSERTED RECORD WITH DETAILS
SELECT EMPLOYEES.*, ROWID FROM EMPLOYEES
WHERE ROWID IN (SELECT MAX(ROWID) FROM EMPLOYEES);

--DISPLAY DEPARTMENT WISE LATEST/LAST INSERTED RECORD WITH DETAILS
SELECT EMPLOYEES.*, ROWID FROM EMPLOYEES
WHERE ROWID IN (SELECT MAX(ROWID) FROM EMPLOYEES GROUP BY DEPARTMENT_ID);

--DISPLAY DEPARTMENT WISE OLDEST/FIRST INSERTED RECORD WITH DETAILS
SELECT EMPLOYEES.*, ROWID FROM EMPLOYEES
WHERE ROWID IN (SELECT MIN(ROWID) FROM EMPLOYEES GROUP BY DEPARTMENT_ID);

-- DISPLAY LATEST/LAST INSERTED RECORD OF PARTICULAR DEPARTMENT WITH DETAILS
SELECT * FROM EMPLOYEES
WHERE ROWID IN (SELECT MAX(ROWID) FROM EMPLOYEES WHERE DEPARTMENT_ID = 30);

--OR

SELECT EMPLOYEES.*, ROWID FROM EMPLOYEES
WHERE ROWID IN (SELECT MAX(ROWID) FROM EMPLOYEES WHERE DEPARTMENT_ID = 30);

-- DISPLAY OLDEST/FIRST INSERTED RECORD OF PARTICULAR DEPARTMENT WITH DETAILS
SELECT * FROM EMPLOYEES 
WHERE ROWID IN (SELECT MIN(ROWID) FROM EMPLOYEES WHERE DEPARTMENT_ID = 30);

--OR

SELECT EMPLOYEES.*, ROWID FROM EMPLOYEES
WHERE ROWID IN (SELECT MIN(ROWID) FROM EMPLOYEES WHERE DEPARTMENT_ID = 30);