SELECT * FROM EMPLOYEES;

--DISPLAY ROWNUM WITH DETAILS
SELECT EMPLOYEES.*, ROWNUM FROM EMPLOYEES;

--DISPLAY ROWNUM IN DESCENDING ORDER WITH DETAILS
SELECT EMPLOYEES.*, ROWNUM FROM EMPLOYEES 
ORDER BY ROWNUM DESC;

--DISPLAY FIRST 5 RECORDS
SELECT EMPLOYEES.* FROM EMPLOYEES WHERE ROWNUM <= 5;

--DISPLAY LAST 5 RECORDS
SELECT * FROM (SELECT EMPLOYEES.* FROM EMPLOYEES ORDER BY ROWNUM DESC)
WHERE ROWNUM <= 5;

--SKIP FIRST 'N' ROWS AND FETCH NEXT 'M' ROWS
SELECT * FROM (
 SELECT EMPLOYEES.*, ROWNUM AS REC_NO FROM EMPLOYEES 
 WHERE ROWNUM <= 20 --END ROWNUM
 ORDER BY ROWNUM
) WHERE  REC_NO > 10; --START ROWNUM

