SELECT * FROM TAB_A;
SELECT * FROM TAB_B;

--DISPLAY UNIQUE RECORDS
SELECT CITY FROM TAB_A 
UNION 
SELECT CITY FROM TAB_B;

--DISPLAY UNIQUE AND DUPLICATE RECORDS
SELECT CITY FROM TAB_A 
UNION ALL
SELECT CITY FROM TAB_B;

--DISPLAY DISTINCT DATA
SELECT CITY FROM TAB_A 
INTERSECT 
SELECT CITY FROM TAB_B;

--DISPLAY DATA PRESENT IN FIRST TABLE BUT NOT PRESENT IN SECOND TABLE
SELECT CITY FROM TAB_A 
MINUS  
SELECT CITY FROM TAB_B;